DROP TABLE WORKER_NODE;
CREATE TABLE WORKER_NODE (
  ID NUMBER(20,0) NOT NULL,
  HOST_NAME VARCHAR2(64) NOT NULL,
  PORT VARCHAR2(64) NOT NULL,
  TYPE NUMBER(11,0) NOT NULL,
  LAUNCH_DATE DATE NOT NULL,
  MODIFIED DATE NOT NULL,
  CREATED DATE NOT NULL
);
COMMENT ON COLUMN WORKER_NODE.ID IS 'auto increment id';
COMMENT ON COLUMN WORKER_NODE.HOST_NAME IS 'host name';
COMMENT ON COLUMN WORKER_NODE.PORT IS 'port';
COMMENT ON COLUMN WORKER_NODE.TYPE IS 'node type: CONTAINER(1), ACTUAL(2), FAKE(3)';
COMMENT ON COLUMN WORKER_NODE.LAUNCH_DATE IS 'launch date';
COMMENT ON COLUMN WORKER_NODE.MODIFIED IS 'modified time';
COMMENT ON COLUMN WORKER_NODE.CREATED IS 'created time';
COMMENT ON TABLE WORKER_NODE IS 'DB WorkerID Assigner for UID Generator';


-- ----------------------------
-- Primary Key structure for table worker_node
-- ----------------------------
ALTER TABLE WORKER_NODE ADD CONSTRAINT "SYS_C0031332" PRIMARY KEY ("ID");

CREATE SEQUENCE WORKER_NODE_ID_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCYCLE
NOCACHE;

-- CREATE OR REPLACE TRIGGER WORKER_NODE_ID_SEQ_TRG
-- BEFORE INSERT ON WORKER_NODE
-- FOR EACH ROW
-- BEGIN
--   SELECT WORKER_NODE_ID_SEQ.NEXTVAL
--   INTO :NEW.ID
--   FROM DUAL;
-- END;

